
default: &default
  adapter: postgresql
  encoding: unicode
  USERNAME: UBUNTU

  pool: 5

development:
  <<: *default
  database: beltreviewtwo_development


test:
  <<: *default
  database: beltreviewtwo_test


production:
  <<: *default
  database: beltreviewtwo_production
  password: <%= ENV['BELTREVIEWTWO_DATABASE_PASSWORD'] %>
